# fly.toml app configuration file generated for taller-mecanico-api-beta on 2024-06-12T17:05:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taller-mecanico-api-beta'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
