# fly.toml app configuration file generated for proyecto-taller-mecanico-server-damp-dawn-7486 on 2024-05-03T12:50:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proyecto-taller-mecanico-server-damp-dawn-7486'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
